---
- name: install gerrit
  hosts: all

  vars:
    gerrit_version: "2.10"
    gerrit_work_dir: /opt/gerrit/work
    gerrit_wget_dir: /opt/gerrit/downloads
    gerrit_host: localhost

  tasks:
    - name: install packages
      yum:
        name={{item}}
        state=present
      with_items:
        - java-1.7.0-openjdk
      notify: yum clean all

    - name: create gerrit working directory
      file:
        state=directory
        path={{gerrit_work_dir}}

    - name: create gerrit download directory
      file:
        state=directory
        path={{gerrit_wget_dir}}

    - name: download gerrit
      get_url:
        url=http://gerrit-releases.storage.googleapis.com/gerrit-{{gerrit_version}}.war
        dest={{gerrit_wget_dir}}

    - name: install gerrit
      shell: java -jar  {{gerrit_wget_dir}}/gerrit-{{gerrit_version}}.war init \
        --batch \
        -d {{gerrit_work_dir}}

    - name: install supervisord
      yum:
        name=supervisor
        state=present
      notify: yum clean all

    - name: configure supervisord
      copy:
        dest=/etc/supervisord.conf
        content='[supervisord]\nnodaemon=true\n[program:gerrit]\ncommand=/bin/bash -c /start.sh\n'
    
  handlers:
    - name: yum clean all
      command: yum clean all





