---
- name: run gerrit docker container
  hosts: all
  gather_facts: no

  vars:
    data_src_dir: ~/work/git
    data_dst_dir: /opt/gerrit/work/git

  tasks:
    - name: start docker container
      docker:
        image=abaranov/gerrit
        name=gerrit
        detach=yes
        ports="80:8080,29418:29418"
        state=running
        volumes={{data_src_dir}}:{{data_dst_dir}}

