---
- name: run gerrit docker container
  hosts: all
  gather_facts: no

  vars:
    git_src_dir: /home/anton/work/my/volumes/gerrit/git
    git_dst_dir: /opt/gerrit/work/git

    db_src_dir:  /home/anton/work/my/volumes/gerrit/db
    db_dst_dir:  /opt/gerrit/work/db

  tasks:
    - name: start docker container
      docker:
        image=abaranov/gerrit
        name=gerrit
        detach=yes
        ports="80:8080,29418:29418"
        state=running
        volumes="{{git_src_dir}}:{{git_dst_dir}},{{db_src_dir}}:{{db_dst_dir}}"

